### ISSUE TITLE
more verbose output on startup

### ISSUE THREAD

**Issue by johanaugustsandels** [bamboo-crypto/bamboo#63]
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/108116474/178837235-c05effe2-2bfa-467d-9ccc-6b8d236c23f3.png">

after node restart, the node is ~2 blocks behind, bamboo server cpu usage 700% and no output

apparently server is going through peers
https://user-images.githubusercontent.com/108116474/178837584-ddaa825c-83a0-4d71-82e1-1e530fdc0d38.mov

server should say something / print out the progress that is visible in :3000/

related #62

**Comment by mr-pandabear** [comment]
Closing as we've added new header sync statuses
